/*
 * This file is part of ArdaMaps, licensed under the MIT License (MIT).
 *
 * Copyright (c) Paul-Bantz <https://github.com/Paul-Bantz>
 * Copyright (c) contributors
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

package com.duom.ardamaps.core.data.config;

import com.google.gson.annotations.SerializedName;
import lombok.Getter;

import java.util.ArrayList;
import java.util.List;

/**
 * Definition of the dimension in the configuration.
 * <br/>The dimension is defined as :
 * <ul>
 *     <li>"scale_factor": The scale factor of the dimension (e.g., 58 for Ardacraft world)</li>
 *     <li>"x_min": The minimum X coordinate of the dimension</li>
 *     <li>"x_max": The maximum X coordinate of the dimension</li>
 *     <li>"z_min": The minimum Z coordinate of the dimension</li>
 *     <li>"z_max": The maximum Z coordinate of the dimension</li>
 * </ul>
 * Example JSON:
 * <pre>
 *   {
 *       "scale_factor": 58,
 *       "x_min": -19584,
 *       "x_max": 34303,
 *       "z_min": -10240,
 *       "z_max": 32767
 *   }
 * </pre>
 */
@Getter
public class Dimension {

    /** Dimension scale 1/scale factor */
    private final transient float scale;

    /** Dimension width  */
    private final transient int width;

    /** Dimension height */
    private final transient int height;

    /** Whether this dimension definition is the default one (i.e., not defined in the config file) */
    private final transient boolean isAutoGenerated;

    /** Dimension scale factor - this is a JSON only configuration */
    @SerializedName("scale_factor")
    private final float scaleFactor;

    /** Dimension name */
    @SerializedName("name")
    private final String name;

    /** Dimension ID (e.g., "minecraft:overworld")  */
    @SerializedName("id")
    private final String id;

    /** Whether the dimension definition has a region definition (i.e., whether it has arda-regions data associated or not) */
    @SerializedName("arda-regions")
    private final boolean supportsArdaRegions;

    /** Dimension min X */
    @SerializedName("x_min")
    private final int xMin;

    /** Dimension max X */
    @SerializedName("x_max")
    private final int xMax;

    /** Dimension min Z */
    @SerializedName("z_min")
    private final int zMin;

    /** Dimension max Z */
    @SerializedName("z_max")
    private final int zMax;

    /** Available map layers for this dimension */
    @SerializedName("map_layers")
    private final List<MapLayerDefinition> mapLayers;

    /**
     * Constructor for Dimension
     *
     * @param name        the name of the dimension
     * @param id          the id of the dimension
     * @param scaleFactor the scale factor of the dimension
     * @param xMin        the minimum X coordinate of the dimension
     * @param xMax        the maximum X coordinate of the dimension
     * @param zMin        the minimum Z coordinate of the dimension
     * @param zMax        the maximum Z coordinate of the dimension<
     */
    public Dimension(String name, String id, float scaleFactor, int xMin, int xMax, int zMin, int zMax, boolean supportsArdaRegions) {
        this(name, id, scaleFactor, xMin, xMax, zMin, zMax, supportsArdaRegions, false);
    }

    /**
     * Constructor for Dimension
     *
     * @param name        the name of the dimension
     * @param id          the id of the dimension
     * @param scaleFactor the scale factor of the dimension
     * @param xMin        the minimum X coordinate of the dimension
     * @param xMax        the maximum X coordinate of the dimension
     * @param zMin        the minimum Z coordinate of the dimension
     * @param zMax        the maximum Z coordinate of the dimension
     * @param isAutoGenerated   whether this dimension definition is the default one (i.e., not defined in the config file)
     */
    public Dimension(String name, String id, float scaleFactor, int xMin, int xMax, int zMin, int zMax, boolean supportsArdaRegions, boolean isAutoGenerated) {

        this.isAutoGenerated = isAutoGenerated;

        this.name = name;
        this.id = id;

        this.scaleFactor = scaleFactor;
        this.scale = 1f / scaleFactor;

        this.xMin = xMin;
        this.xMax = xMax;

        this.width = xMax - xMin - 1;

        this.zMin = zMin;
        this.zMax = zMax;

        this.height = zMax - zMin - 1;

        this.supportsArdaRegions = supportsArdaRegions;

        this.mapLayers = new ArrayList<>();
    }
}
