/*
 * This file is part of ArdaMaps, licensed under the MIT License (MIT).
 *
 * Copyright (c) Paul-Bantz <https://github.com/Paul-Bantz>
 * Copyright (c) contributors
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

package com.duom.ardamaps.core.data.config.client;

import com.duom.ardamaps.ArdaMapsClient;
import com.duom.ardamaps.core.Client;
import com.duom.ardamaps.core.data.ExplorationState;
import com.duom.ardamaps.core.data.PlayerExploration;
import com.duom.ardamaps.core.data.config.Dimension;
import lombok.Getter;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.Serial;
import java.io.Serializable;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

/**
 * Class representing the client's exploration progress, including per-dimension exploration states.
 * This class is serializable for persistence purposes.
 */
@Getter
public class ClientProgress implements Serializable {

    /** Class logger */
    private static final Logger LOGGER = LoggerFactory.getLogger(ClientProgress.class);

    @Serial
    private static final long serialVersionUID = 2L;

    /** Map of dimension ID to exploration byte array. */
    private final Map<String, PlayerExploration> explorationState = new HashMap<>();

    /** IDs of locations the player has visited */
    private final Set<String> visitedLocationIds = new HashSet<>();

    /**
     * Initializes textures for all exploration states.
     * Should be run at client startup when RenderSystem is available
     */
    public void initializeTextures() {

        for (PlayerExploration exploration : explorationState.values()) {
            exploration.initializeTexture();
        }
    }

    /**
     * Disposes and removes all per-dimension {@link PlayerExploration} instances
     * This essentially resets the client's exploration progress for all dimensions
     */
    public void reset(boolean autoGenOnly) {

        explorationState.entrySet().removeIf(entry -> {

            PlayerExploration exploration = entry.getValue();

            boolean shouldRemove = !autoGenOnly || exploration.isAutoGenerated();

            if (shouldRemove){
                LOGGER.warn("Disposing exploration state for dimension {} (auto-generated: {})", entry.getKey(), exploration.isAutoGenerated());
                exploration.dispose();
            }

            return shouldRemove;
        });

        if (!autoGenOnly) {

            ArdaMapsClient.CONFIG.getLocations().forEach(location -> {
                location.setVisited(false);
                location.setExplorationState(ExplorationState.HIDDEN);
            });

            ArdaMapsClient.CONFIG_MANAGER.saveProgress();
        }

        initialize();

        // Reset ArdaRegions progress
        if (!autoGenOnly && Client.player() != null)
            Client.player().networkHandler.sendChatCommand("ardaregions resetprogress");
    }

    /**
     * Initializes the exploration state for all known dimensions
     */
    private void initialize() {

        if (ArdaMapsClient.CONFIG.getDimensions().isEmpty())
            return;

        for (Dimension dimension : ArdaMapsClient.CONFIG.getDimensions()) {

            // Skip if exploration state already exists for this dimension (e.g., from previous initialization or reset).
            if (explorationState.containsKey(dimension.getId())) continue;

            PlayerExploration exploration = PlayerExploration.create(dimension, null);
            this.explorationState.put(dimension.getId(), exploration);
        }
    }

    /**
     * Retrieves the exploration state for a specific dimension.
     *
     * @param dimensionId The ID of the dimension to retrieve the exploration state for.
     * @return The PlayerExploration instance for the specified dimension, or null if not found.
     */
    public PlayerExploration getExplorationState(String dimensionId, boolean createDefault) {

        return createDefault ? explorationState.computeIfAbsent(dimensionId, PlayerExploration::create) : explorationState.get(dimensionId);
    }
}