/*
 * This file is part of ArdaMaps, licensed under the MIT License (MIT).
 *
 * Copyright (c) Paul-Bantz <https://github.com/Paul-Bantz>
 * Copyright (c) contributors
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

package com.duom.ardamaps.core.networking.packets.client;

import com.duom.ardamaps.core.consumers.networking.IPacket;
import com.duom.ardamaps.core.consumers.networking.IRespondablePacket;
import com.duom.ardamaps.core.data.config.Dimension;
import com.duom.ardamaps.core.data.config.MapLayerDefinition;
import com.duom.ardamaps.core.data.config.MapLayerRange;
import com.duom.ardamaps.core.data.config.MapLayerSource;
import com.duom.ardamaps.gui.ModConstants;
import net.fabricmc.fabric.api.networking.v1.FriendlyByteBufs;
import net.minecraft.network.FriendlyByteBuf;
import net.minecraft.network.RegistryFriendlyByteBuf;
import net.minecraft.network.codec.StreamCodec;
import net.minecraft.network.protocol.common.custom.CustomPacketPayload;
import org.jspecify.annotations.NonNull;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * A packet sent from the server to the client containing the map source configuration in JSON format.
 * @param warpsAvailable       whether server-side warps are available
 * @param ardaRegionsAvailable whether server-side ArdaRegions is available
 * @param dimensions           the list of dimensions to transfer
 */
public record MapSourceResponsePacket(UUID requestId,
                                      boolean warpsAvailable,
                                      boolean ardaRegionsAvailable,
                                      List<Dimension> dimensions) implements IRespondablePacket<MapSourceResponsePacket> {
    public static final CustomPacketPayload.Type<MapSourceResponsePacket> TYPE = new CustomPacketPayload.Type<>(ModConstants.modId("map_source_response"));
    public static final StreamCodec<RegistryFriendlyByteBuf, MapSourceResponsePacket> CODEC = IPacket.codec(MapSourceResponsePacket::read);

    /** Class logger */
    private static final Logger LOGGER = LoggerFactory.getLogger(MapSourceResponsePacket.class);

    /** Maximum number of dimensions accepted from the wire. */
    private static final int MAX_DIMENSIONS = 128;

    /** Maximum number of map layers accepted for a single dimension. */
    private static final int MAX_LAYERS_PER_DIMENSION = 128;

    /** Maximum number of ranged layer entries accepted for a single layer. */
    private static final int MAX_RANGES_PER_LAYER = 512;

    public MapSourceResponsePacket(boolean warpsAvailable, boolean ardaRegionsAvailable, List<Dimension> dimensions) {
        this(new UUID(0L, 0L), warpsAvailable, ardaRegionsAvailable, dimensions);
    }

    /**
     * Reads a MapSourceResponsePacket - ie a maps layer configuration from the given PacketByteBuf.
     *
     * @param buf The PacketByteBuf to read from
     * @return The MapSourceResponsePacket read from the buffer
     */
    public static MapSourceResponsePacket read(FriendlyByteBuf buf) {

        var requestId = buf.readUUID();
        var warpsAvailable = buf.readBoolean();
        var ardaRegionsAvailable = buf.readBoolean();
        var dimensionsCount = readCount(buf, "dimensions", MAX_DIMENSIONS);
        var dimensions = new ArrayList<Dimension>(dimensionsCount);

        for (int idx = 0; idx < dimensionsCount; idx++) {

            var scaleFactor = buf.readFloat();
            var name = buf.readUtf();
            var id = buf.readUtf();
            var ardaRegions = buf.readBoolean();
            var xMin = buf.readInt();
            var xMax = buf.readInt();
            var zMin = buf.readInt();
            var zMax = buf.readInt();
            var autoGenerated = buf.readBoolean();

            Dimension dimension = new Dimension(name, id, scaleFactor, xMin, xMax, zMin, zMax, ardaRegions, autoGenerated);

            var layersCount = readCount(buf, "map layers", MAX_LAYERS_PER_DIMENSION);
            for (int jdx = 0; jdx < layersCount; jdx++) {

                var layerName = buf.readUtf();
                var typeName = buf.readUtf();
                var type = parseMapLayerSource(typeName);
                var remote = buf.readBoolean();
                var identityZoom = buf.readInt();
                var preferredZoom = buf.readDouble();
                var lodFactor = buf.readDouble();
                var minLod = buf.readInt();
                var maxLod = buf.readInt();
                var minZoom = buf.readInt();
                var maxZoom = buf.readInt();
                var tileSize = buf.readInt();
                var scale = buf.readDouble();
                var path = buf.readBoolean() ? buf.readUtf() : null;
                var icon = buf.readUtf();

                var rangesCount = readCount(buf, "map layer ranges", MAX_RANGES_PER_LAYER);
                List<MapLayerRange> ranges = null;

                if (rangesCount > 0) {
                    ranges = new ArrayList<>(rangesCount);

                    for (int kdx = 0; kdx < rangesCount; kdx++) {
                        ranges.add(new MapLayerRange(
                                buf.readInt(),
                                buf.readUtf(),
                                buf.readInt(),
                                buf.readInt()));
                    }
                }

                if (type == null) {
                    LOGGER.warn("Skipping map layer '{}' with unknown source type '{}'", layerName, typeName);
                    continue;
                }

                MapLayerDefinition layer = new MapLayerDefinition(layerName, type, remote, identityZoom, preferredZoom, lodFactor, minLod, maxLod, minZoom, maxZoom, tileSize, scale, path, icon, ranges);
                dimension.getMapLayers().add(layer);
            }

            dimensions.add(dimension);
        }

        return new MapSourceResponsePacket(requestId, warpsAvailable, ardaRegionsAvailable, dimensions);
    }

    /**
     * Builds a PacketByteBuf from this MapSourceResponsePacket - ie a maps layer configuration.
     *
     * @return The PacketByteBuf representing this MapSourceResponsePacket
     */
    @Override
    public FriendlyByteBuf build() {

        FriendlyByteBuf buf = FriendlyByteBufs.create();

        buf.writeUUID(requestId);
        buf.writeBoolean(warpsAvailable);
        buf.writeBoolean(ardaRegionsAvailable);

        var dimensionsCount = dimensions == null || dimensions.isEmpty() ? 0 : dimensions.size();
        buf.writeInt(dimensionsCount);

        for (int idx = 0; idx < dimensionsCount; idx++) {

            var dimension = dimensions.get(idx);
            buf.writeFloat(dimension.getScaleFactor());
            buf.writeUtf(dimension.getName());
            buf.writeUtf(dimension.getId());
            buf.writeBoolean(dimension.isSupportsArdaRegions());
            buf.writeInt(dimension.getXMin());
            buf.writeInt(dimension.getXMax());
            buf.writeInt(dimension.getZMin());
            buf.writeInt(dimension.getZMax());
            buf.writeBoolean(dimension.isAutoGenerated());

            var layers = dimension.getMapLayers();
            var layersCount = layers == null || layers.isEmpty() ? 0 : layers.size();
            buf.writeInt(layersCount);

            for (int jdx = 0; jdx < layersCount; jdx++) {

                var layer = layers.get(jdx);
                buf.writeUtf(layer.layer());
                buf.writeUtf(layer.type().name());
                buf.writeBoolean(layer.remote());
                buf.writeInt(layer.identityZoom());
                buf.writeDouble(layer.preferredZoom());
                buf.writeDouble(layer.lodFactor());
                buf.writeInt(layer.minLod());
                buf.writeInt(layer.maxLod());
                buf.writeInt(layer.minZoom());
                buf.writeInt(layer.maxZoom());
                buf.writeInt(layer.tileSize());
                buf.writeDouble(layer.scale());
                buf.writeBoolean(layer.path() != null);
                if (layer.path() != null) buf.writeUtf(layer.path());
                buf.writeUtf(layer.icon());

                var ranges = layer.ranges();
                var rangesCount = ranges == null || ranges.isEmpty() ? 0 : ranges.size();
                buf.writeInt(rangesCount);

                for (int kdx = 0; kdx < rangesCount; kdx++) {
                    var range = ranges.get(kdx);
                    buf.writeInt(range.index());
                    buf.writeUtf(range.path());
                    buf.writeInt(range.rangeMinY());
                    buf.writeInt(range.rangeMaxY());
                }
            }
        }

        return buf;
    }

    @Override
    public MapSourceResponsePacket withRequestId(UUID requestId) {
        return new MapSourceResponsePacket(requestId, warpsAvailable, ardaRegionsAvailable, dimensions);
    }

    @Override
    public CustomPacketPayload.@NonNull Type<MapSourceResponsePacket> type() {
        return TYPE;
    }

    /**
     * Reads and validates an integer collection size from the packet.
     *
     * @param buf   The packet buffer.
     * @param label Human-readable field label for error messages.
     * @param max   Maximum accepted count.
     * @return The validated count.
     */
    private static int readCount(FriendlyByteBuf buf, String label, int max) {

        int count = buf.readInt();

        if (count < 0) {
            throw new IllegalArgumentException("Map source " + label + " count cannot be negative: " + count);
        }

        if (count > max) {
            throw new IllegalArgumentException("Map source " + label + " count exceeds maximum of " + max + ": " + count);
        }

        return count;
    }

    /**
     * Parses a map layer source from the wire without failing the whole packet on version skew.
     *
     * @param typeName Serialized enum name.
     * @return The matching source, or {@code null} when unknown.
     */
    private static MapLayerSource parseMapLayerSource(String typeName) {

        try {
            return MapLayerSource.valueOf(typeName);
        } catch (IllegalArgumentException e) {
            return null;
        }
    }
}
