/*
 * This file is part of ArdaMaps, licensed under the MIT License (MIT).
 *
 * Copyright (c) Paul-Bantz <https://github.com/Paul-Bantz>
 * Copyright (c) contributors
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

package com.duom.ardamaps.core.networking.packets.client;

import com.duom.ardamaps.core.consumers.networking.IPacket;
import com.duom.ardamaps.core.data.config.Dimension;
import com.duom.ardamaps.core.data.config.MapLayerDefinition;
import com.duom.ardamaps.core.data.config.MapLayerSource;
import net.fabricmc.fabric.api.networking.v1.PacketByteBufs;
import net.minecraft.network.PacketByteBuf;

import java.util.ArrayList;
import java.util.List;

/**
 * A packet sent from the server to the client containing the map source configuration in JSON format.
 */
public record MapSourceResponsePacket(List<Dimension> dimensions) implements IPacket {
    /**
     * Reads a MapSourceResponsePacket - ie a maps layer configuration from the given PacketByteBuf.
     *
     * @param buf The PacketByteBuf to read from
     * @return The MapSourceResponsePacket read from the buffer
     */
    public static MapSourceResponsePacket read(PacketByteBuf buf) {

        var dimensionsCount = buf.readInt();
        var dimensions = new ArrayList<Dimension>(dimensionsCount);

        for (int idx = 0; idx < dimensionsCount; idx++) {

            var scaleFactor = buf.readFloat();
            var name = buf.readString();
            var id = buf.readString();
            var ardaRegions = buf.readBoolean();
            var xMin = buf.readInt();
            var xMax = buf.readInt();
            var zMin = buf.readInt();
            var zMax = buf.readInt();
            var autoGenerated = buf.readBoolean();

            Dimension dimension = new Dimension(name, id, scaleFactor, xMin, xMax, zMin, zMax, ardaRegions, autoGenerated);

            var layersCount = buf.readInt();
            for (int jdx = 0; jdx < layersCount; jdx++) {

                var layerName = buf.readString();
                var type = MapLayerSource.valueOf(buf.readString());
                var remote = buf.readBoolean();
                var identityZoom = buf.readInt();
                var lodFactor = buf.readDouble();
                var minLod = buf.readInt();
                var maxLod = buf.readInt();
                var minZoom = buf.readInt();
                var maxZoom = buf.readInt();
                var tileSize = buf.readInt();
                var scale = buf.readDouble();
                var path = buf.readString();
                var icon = buf.readString();

                MapLayerDefinition layer = new MapLayerDefinition(layerName, type, remote, identityZoom, lodFactor, minLod, maxLod, minZoom, maxZoom, tileSize, scale, path, icon);
                dimension.getMapLayers().add(layer);
            }

            dimensions.add(dimension);
        }

        return new MapSourceResponsePacket(dimensions);
    }

    /**
     * Builds a PacketByteBuf from this MapSourceResponsePacket - ie a maps layer configuration.
     *
     * @return The PacketByteBuf representing this MapSourceResponsePacket
     */
    @Override
    public PacketByteBuf build() {

        PacketByteBuf buf = PacketByteBufs.create();

        var dimensionsCount = dimensions == null || dimensions.isEmpty() ? 0 : dimensions.size();
        buf.writeInt(dimensionsCount);

        for (int idx = 0; idx < dimensionsCount; idx++) {

            var dimension = dimensions.get(idx);
            buf.writeFloat(dimension.getScaleFactor());
            buf.writeString(dimension.getName());
            buf.writeString(dimension.getId());
            buf.writeBoolean(dimension.isSupportsArdaRegions());
            buf.writeInt(dimension.getXMin());
            buf.writeInt(dimension.getXMax());
            buf.writeInt(dimension.getZMin());
            buf.writeInt(dimension.getZMax());
            buf.writeBoolean(dimension.isAutoGenerated());

            var layers = dimension.getMapLayers();
            var layersCount = layers == null || layers.isEmpty() ? 0 : layers.size();
            buf.writeInt(layersCount);

            for (int jdx = 0; jdx < layersCount; jdx++) {

                var layer = layers.get(jdx);
                buf.writeString(layer.layer());
                buf.writeString(layer.type().name());
                buf.writeBoolean(layer.remote());
                buf.writeInt(layer.identityZoom());
                buf.writeDouble(layer.lodFactor());
                buf.writeInt(layer.minLod());
                buf.writeInt(layer.maxLod());
                buf.writeInt(layer.minZoom());
                buf.writeInt(layer.maxZoom());
                buf.writeInt(layer.tileSize());
                buf.writeDouble(layer.scale());
                buf.writeString(layer.path());
                buf.writeString(layer.icon());
            }
        }

        return buf;
    }
}