/*
 * This file is part of ArdaMaps, licensed under the MIT License (MIT).
 *
 * Copyright (c) Paul-Bantz <https://github.com/Paul-Bantz>
 * Copyright (c) contributors
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

package com.duom.ardamaps.core.data.config;

import com.duom.ardamaps.ArdaMaps;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.TimeUnit;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;

/**
 * Tests for server configuration loading defaults and hardening.
 */
class ServerConfigManagerTest {

    /** Temporary configuration directory. */
    @TempDir
    private Path tempDir;

    /**
     * Waits for async configuration saves before JUnit deletes the temporary directory.
     *
     * @throws Exception If the IO executor does not drain.
     */
    @AfterEach
    void waitForConfigSaves() throws Exception {

        CompletableFuture.runAsync(() -> {
        }, ArdaMaps.IO_EXECUTOR).get(2, TimeUnit.SECONDS);
    }

    /**
     * Verifies that a missing server config creates an editable overworld grid definition.
     */
    @Test
    void missingServerConfig_createsDefaultOverworldGridDimension() {

        ServerConfigManager manager = manager();

        assertEquals(1, manager.getConfig().getDimensions().size());

        Dimension dimension = manager.getConfig().getDimensions().getFirst();
        assertEquals("minecraft:overworld", dimension.getId());
        assertEquals("overworld", dimension.getName());
        assertEquals(1f, dimension.getScaleFactor());
        assertEquals(-25000, dimension.getXMin());
        assertEquals(24999, dimension.getXMax());
        assertEquals(-25000, dimension.getZMin());
        assertEquals(24999, dimension.getZMax());
        assertEquals(50000, dimension.getWidth());
        assertEquals(50000, dimension.getHeight());
        assertFalse(dimension.isSupportsArdaRegions());
        assertFalse(dimension.isAutoGenerated());
        assertEquals(1, dimension.getMapLayers().size());
        assertEquals(MapLayerDefinition.DEFAULT_GRID_LAYER, dimension.getMapLayers().getFirst());
    }

    /**
     * Verifies that an existing server config without dimensions loads as an empty list.
     *
     * @throws IOException If the test config cannot be written.
     */
    @Test
    void serverConfigWithoutDimensions_loadsEmptyDimensionsList() throws IOException {

        Files.createDirectories(configDir());
        Files.writeString(configPath(), """
                {
                  "refresh_cron": "0 3 */4 * *"
                }
                """);

        ServerConfigManager manager = manager();

        assertEquals(0, manager.getConfig().getDimensions().size());
    }

    /**
     * Creates a server config manager rooted in the temporary directory.
     *
     * @return A server config manager.
     */
    private ServerConfigManager manager() {

        return new ServerConfigManager(
                configPath().toString(),
                configDir().resolve("server-locations.json").toString(),
                configDir().resolve("region-texture-lookup.json").toString());
    }

    /**
     * Gets the test server config path.
     *
     * @return The test server config path.
     */
    private Path configPath() {

        return configDir().resolve("server.json");
    }

    /**
     * Gets the test ArdaMaps config directory.
     *
     * @return The test ArdaMaps config directory.
     */
    private Path configDir() {

        return tempDir.resolve("arda-maps");
    }
}
