/*
 * This file is part of ArdaMaps, licensed under the MIT License (MIT).
 *
 * Copyright (c) Paul-Bantz <https://github.com/Paul-Bantz>
 * Copyright (c) contributors
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

package com.duom.ardamaps.core.data.json;

import com.duom.ardamaps.core.data.config.Dimension;
import com.duom.ardamaps.core.data.config.DimensionRemap;
import com.duom.ardamaps.core.data.config.MapLayerDefinition;
import com.google.gson.*;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Custom TypeAdapter for deserializing Dimensions from JSON.
 */
public class DimensionTypeAdapter implements JsonDeserializer<Dimension>, JsonSerializer<Dimension> {

    /**
     * Deserialize Json data to Dimension object
     *
     * @param json    The Json data being deserialized
     * @param typeOfT The type of the Object to deserialize to
     * @param context The context for deserialization
     * @return The deserialized Dimension object
     * @throws JsonParseException if there is an error during deserialization
     */
    @Override
    public Dimension deserialize(JsonElement json, Type typeOfT, JsonDeserializationContext context) throws JsonParseException {

        JsonObject obj = JsonAdapterUtils.object(json, "dimension");

        String name = JsonAdapterUtils.required(obj, "name").getAsString();
        String id = JsonAdapterUtils.required(obj, "id").getAsString();
        float scaleFactor = JsonAdapterUtils.required(obj, "scale_factor").getAsFloat();
        int xMin = JsonAdapterUtils.required(obj, "x_min").getAsInt();
        int xMax = JsonAdapterUtils.required(obj, "x_max").getAsInt();
        int zMin = JsonAdapterUtils.required(obj, "z_min").getAsInt();
        int zMax = JsonAdapterUtils.required(obj, "z_max").getAsInt();
        boolean ardaRegions = obj.has("arda-regions") && obj.get("arda-regions").getAsBoolean();
        boolean autoGenerated = obj.has("auto_generated") && obj.get("auto_generated").getAsBoolean();
        List<DimensionRemap> remaps = obj.has("remaps") ? parseRemaps(obj.get("remaps")) : Collections.emptyList();

        var dimension = new Dimension(name, id, scaleFactor, xMin, xMax, zMin, zMax, ardaRegions, autoGenerated, remaps);

        if (obj.has("map_layers")) {

            var mapLayersJson = obj.get("map_layers").getAsJsonArray();
            for (JsonElement layerElement : mapLayersJson) {

                MapLayerDefinition layer = context.deserialize(layerElement, MapLayerDefinition.class);
                dimension.getMapLayers().add(layer);
            }
        }

        return dimension;
    }

    /**
     * Serialize a Dimension object to Json data.
     *
     * @param src       The Dimension being serialized.
     * @param typeOfSrc The type of the Object to serialize.
     * @param context   The context for serialization.
     * @return The serialized Dimension JSON object.
     */
    @Override
    public JsonElement serialize(Dimension src, Type typeOfSrc, JsonSerializationContext context) {

        JsonObject obj = new JsonObject();
        obj.addProperty("name", src.getName());
        obj.addProperty("id", src.getId());
        obj.addProperty("scale_factor", src.getScaleFactor());
        obj.addProperty("x_min", src.getXMin());
        obj.addProperty("x_max", src.getXMax());
        obj.addProperty("z_min", src.getZMin());
        obj.addProperty("z_max", src.getZMax());
        obj.addProperty("arda-regions", src.isSupportsArdaRegions());

        if (!src.getRemaps().isEmpty()) {
            obj.add("remaps", serializeRemaps(src.getRemaps()));
        }

        obj.add("map_layers", context.serialize(src.getMapLayers()));

        return obj;
    }

    /**
     * Parses structured dimension remap configuration.
     *
     * @param remaps The remaps JSON element.
     * @return The parsed remaps.
     */
    private static List<DimensionRemap> parseRemaps(JsonElement remaps) {

        if (remaps == null || remaps.isJsonNull()) return Collections.emptyList();

        JsonArray array = remaps.getAsJsonArray();
        List<DimensionRemap> parsed = new ArrayList<>(array.size());

        for (JsonElement element : array) {
            JsonObject remap = JsonAdapterUtils.object(element, "dimension remap");
            String remapId = JsonAdapterUtils.required(remap, "id").getAsString();

            if (!remap.has("region") || remap.get("region").isJsonNull()) {
                parsed.add(new DimensionRemap(remapId));
                continue;
            }

            JsonObject region = JsonAdapterUtils.object(remap.get("region"), "dimension remap region");
            parsed.add(new DimensionRemap(
                    remapId,
                    JsonAdapterUtils.required(region, "x1").getAsInt(),
                    JsonAdapterUtils.required(region, "z1").getAsInt(),
                    JsonAdapterUtils.required(region, "x2").getAsInt(),
                    JsonAdapterUtils.required(region, "z2").getAsInt()));
        }

        return parsed;
    }

    /**
     * Serializes remaps to the documented structured JSON shape.
     *
     * @param remaps The remaps to serialize.
     * @return The remaps JSON array.
     */
    private static JsonArray serializeRemaps(List<DimensionRemap> remaps) {

        JsonArray array = new JsonArray();

        for (DimensionRemap remap : remaps) {
            JsonObject remapJson = new JsonObject();
            remapJson.addProperty("id", remap.id());

            if (remap.hasRegion()) {
                JsonObject region = new JsonObject();
                region.addProperty("x1", remap.x1());
                region.addProperty("z1", remap.z1());
                region.addProperty("x2", remap.x2());
                region.addProperty("z2", remap.z2());
                remapJson.add("region", region);
            }

            array.add(remapJson);
        }

        return array;
    }
}
