/*
 * This file is part of ArdaMaps, licensed under the MIT License (MIT).
 *
 * Copyright (c) Paul-Bantz <https://github.com/Paul-Bantz>
 * Copyright (c) contributors
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

package com.duom.ardamaps.core.data;

import com.duom.ardamaps.ArdaMapsClient;
import com.duom.ardamaps.core.Client;
import com.duom.ardamaps.core.data.config.Dimension;
import lombok.Getter;
import lombok.Setter;
import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;
import net.minecraft.client.MinecraftClient;
import net.minecraft.client.texture.NativeImage;
import net.minecraft.client.texture.NativeImageBackedTexture;
import net.minecraft.util.Identifier;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.Serial;
import java.io.Serializable;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

/**
 * Manages the player's exploration state for a single dimension, including which areas have been
 * explored and the corresponding fog-of-war texture.
 *
 * <p>Each dimension has its own {@code PlayerExploration} instance, registered in
 * {@link com.duom.ardamaps.core.data.config.client.ClientConfig}.</p>
 */
@Environment(EnvType.CLIENT)
public class PlayerExploration implements Serializable {

    /** Class logger */
    private static final Logger LOGGER = LoggerFactory.getLogger(PlayerExploration.class);

    /** Minimum cell size in world units (blocks). */
    private static final int MIN_CELL_SIZE = 128;

    /** Maximum number of cells allowed along any single axis. */
    private static final int MAX_CELLS_PER_AXIS = 420;

    @Serial
    private static final long serialVersionUID = 1L;

    /** Prefix used when registering the fog-of-war texture in Minecraft's texture manager. */
    private static final String TEXTURE_PREFIX = "fog_of_war_texture";

    /** The dimension ID this instance manages (e.g. {@code "minecraft:overworld"}). */
    @Getter
    private final String dimensionId;

    /** Number of cells along the X axis (width) of the dimension. */
    @Getter
    private final int nbCellsX;

    /** Number of cells along the Z axis (height) of the dimension. */
    @Getter
    private final int nbCellsY;

    /** The world X coordinate corresponding to the minimum cell X index (0). */
    private final int xMin;

    /** The world Z coordinate corresponding to the minimum cell Y index (0). */
    private final int zMin;

    /** Whether this instance was automatically generated (true) or loaded from saved data (false). */
    @Getter
    private final boolean autoGenerated;

    /**
     * Size of each exploration cell in world units (blocks), computed at construction time.
     * At least {@value #MIN_CELL_SIZE}; increased as needed so neither axis exceeds
     * {@value #MAX_CELLS_PER_AXIS} cells.
     */
    @Getter
    private final int cellSize;

    /**
     * The backing byte array that stores the exploration state for each cell.
     */
    @Setter
    private byte[] explorationData;

    /** Set of cell indices that have been modified since the last texture upload. */
    private transient Set<Integer> dirtyCells;

    /**
     * The in-memory (CPU-side) fog-of-war mask image, where each pixel corresponds to a cell.
     * This is updated on the go and used by {@link #fogTexture} to upload changes to the GPU.
     */
    private transient NativeImage fogMask;

    /** The GPU texture for the fog-of-war, created from {@link #fogMask}. */
    private transient NativeImageBackedTexture fogTexture;

    /** The identifier of the fog-of-war texture in Minecraft's texture manager, used for rendering. */
    @Getter
    private transient Identifier fogTextureId;

    /**
     * Creates a new {@link PlayerExploration} for the given dimension.
     *
     * <p>The {@code explorationData} array is used as-is (not copied) so that mutations are
     * visible to whatever holds the same reference (e.g.
     * {@link com.duom.ardamaps.core.data.config.client.ClientProgress}).</p>
     *
     * @param dimension Dimension definition providing world extents
     */
    private PlayerExploration(Dimension dimension) {

        this.dimensionId = dimension.getId();
        this.cellSize = computeCellSize(dimension.getWidth(), dimension.getHeight());
        this.nbCellsX = (int) Math.ceil((double) dimension.getWidth() / cellSize);
        this.nbCellsY = (int) Math.ceil((double) dimension.getHeight() / cellSize);
        this.xMin = dimension.getXMin();
        this.zMin = dimension.getZMin();
        this.autoGenerated = dimension.isAutoGenerated();
        this.dirtyCells = new HashSet<>();
    }

    /**
     * Computes the cell size for the given world dimensions, ensuring neither axis exceeds
     * {@value #MAX_CELLS_PER_AXIS} cells while staying at or above {@value #MIN_CELL_SIZE}.
     *
     * @param width  World width in blocks.
     * @param height World height in blocks.
     * @return The resolved cell size in blocks.
     */
    private int computeCellSize(int width, int height) {
        int needed = (int) Math.ceil((double) Math.max(width, height) / MAX_CELLS_PER_AXIS);
        return Math.max(MIN_CELL_SIZE, needed);
    }

    /**
     * Factory method to create a PlayerExploration instance for the dimension with the given ID.
     *
     * @param dimensionId The ID of the dimension (e.g. "minecraft:overworld").
     * @return A new PlayerExploration instance for the specified dimension, or null if the dimension is not found in the config.
     */
    public static @Nullable PlayerExploration create(String dimensionId) {

        var dimension = ArdaMapsClient.CONFIG.getDimension(dimensionId);

        if (dimension != null)
            return create(dimension, null);

        return null;
    }

    /**
     * Factory method to create a PlayerExploration instance for the given dimension and exploration data, with an option to mark it as auto-generated.
     *
     * @param dimension       Dimension definition providing world extents.
     * @param explorationData Backing array; length must equal nbCellsX * nbCellsY, or null to create an empty exploration.
     * @return A new PlayerExploration instance initialized with the provided data and auto-generation flag.
     */
    public static PlayerExploration create(Dimension dimension, byte[] explorationData) {

        PlayerExploration playerExploration = new PlayerExploration(dimension);

        // Check if input data matches the computed cell-size. If not, we warn, ignore it and start fresh.
        int nbCells = (int) Math.ceil((double) dimension.getWidth() / playerExploration.getCellSize())
                * (int) Math.ceil((double) dimension.getHeight() / playerExploration.getCellSize());

        if (explorationData == null || explorationData.length != nbCells) {

            LOGGER.warn("Invalid exploration data - expected length {}, got {}. Creating empty exploration.", nbCells, explorationData == null ? "null" : explorationData.length);
            playerExploration.setExplorationData(PlayerExploration.emptyExploration(nbCells));

        } else {

            LOGGER.info("Initializing exploration with provided data of length {} for dimension '{}'.", explorationData.length, dimension.getId());
            playerExploration.setExplorationData(explorationData);
        }

        playerExploration.initializeTexture();

        return playerExploration;
    }

    /**
     * Creates an empty exploration byte array where every cell is {@link ExplorationState#HIDDEN}.
     *
     * @param nbCells Total number of cells (nbCellsX * nbCellsY).
     * @return A freshly allocated byte array of length {@code nbCells}.
     */
    private static byte[] emptyExploration(int nbCells) {

        byte[] array = new byte[nbCells];
        Arrays.fill(array, ExplorationState.HIDDEN.getValue());

        return array;
    }

    /**
     * Initializes the fog-of-war texture and synchronizes it with the current exploration data.
     * Should be called on (or via) the render thread after creating a PlayerExploration instance.
     */
    public void initializeTexture() {

        if (dirtyCells == null)
            dirtyCells = new HashSet<>();

        initialize();
        syncTextureFromData();
    }

    /**
     * Initializes the fog-of-war texture. All pixels begin as {@link ExplorationState#HIDDEN}.
     * No fill needed - NativeImage is zero-initialized, and HIDDEN colour is 0x00000000
     * Should be called on (or via) the render thread.
     */
    private void initialize() {

        fogMask = new NativeImage(nbCellsX, nbCellsY, true);

        fogTexture = new NativeImageBackedTexture(fogMask);
        fogTextureId = MinecraftClient.getInstance()
                .getTextureManager()
                .registerDynamicTexture(TEXTURE_PREFIX + "_" + sanitizeDimensionId(dimensionId), fogTexture);
    }

    /**
     * Marks every non-{@link ExplorationState#HIDDEN} cell from {@link #explorationData} as dirty
     * and then calls {@link #flushTexture()} to upload them.
     *
     * <p>Call this once after {@link #initialize()} to restore a previously saved exploration state
     * onto the fog-of-war texture.</p>
     */
    public void syncTextureFromData() {

        for (int i = 0; i < explorationData.length; i++) {
            if (ExplorationState.fromValue(explorationData[i]) != ExplorationState.HIDDEN) {
                dirtyCells.add(i);
            }
        }
        flushTexture();
    }

    /**
     * Sanitizes the dimension ID to ensure it's a valid texture identifier suffix by replacing
     *
     * @param dimensionId The original dimension ID (e.g. "minecraft:overworld").
     * @return A sanitized version of the dimension ID suitable for use in texture identifiers (e.g. "minecraft_overworld").
     */
    private String sanitizeDimensionId(String dimensionId) {
        return dimensionId.replace(':', '_').replace('/', '_');
    }

    /**
     * Uploads all dirty cells to the fog-of-war texture.
     * No-op if there are no dirty cells or if the texture has not been initialized.
     */
    public void flushTexture() {
        if (dirtyCells.isEmpty() || fogMask == null) return;

        for (int idx : dirtyCells) {
            int x = idx % nbCellsX;
            int y = idx / nbCellsX;
            fogMask.setColor(x, y, stateAt(x, y).getColor());
        }

        dirtyCells.clear();
        fogTexture.upload();
    }

    /**
     * Returns the exploration state at the given world position.
     *
     * @param worldX World X coordinate.
     * @param worldZ World Z coordinate.
     * @return The {@link ExplorationState}, or {@link ExplorationState#HIDDEN} if out of bounds.
     */
    public ExplorationState stateAtWorldPos(double worldX, double worldZ) {
        return stateAt(toCellX(worldX), toCellZ(worldZ));
    }

    /**
     * Returns the exploration state of the cell at {@code (cellX, cellY)}.
     *
     * @param cellX Cell X index.
     * @param cellY Cell Y index.
     * @return The {@link ExplorationState}, or {@link ExplorationState#HIDDEN} if out of bounds.
     */
    public @NotNull ExplorationState stateAt(int cellX, int cellY) {

        if (!inBounds(cellX, cellY)) return ExplorationState.HIDDEN;
        return ExplorationState.fromValue(explorationData[index(cellX, cellY)]);
    }

    /**
     * Converts a world X coordinate to the cell-X index.
     *
     * @param worldX World X coordinate.
     * @return Cell X index (may be out of bounds).
     */
    public int toCellX(double worldX) {
        return Math.floorDiv((int) Math.floor(worldX) - xMin, cellSize);
    }

    /**
     * Converts a world Z coordinate to the cell-Y index.
     *
     * @param worldZ World Z coordinate.
     * @return Cell Y index (may be out of bounds).
     */
    public int toCellZ(double worldZ) {
        return Math.floorDiv((int) Math.floor(worldZ) - zMin, cellSize);
    }

    /**
     * Returns {@code true} if the given cell coordinates are within the bounds of the exploration grid.
     *
     * @param cellX Cell X index.
     * @param cellY Cell Y index.
     * @return Whether the cell coordinates are valid and within bounds.
     */
    private boolean inBounds(int cellX, int cellY) {
        return cellX >= 0 && cellX < nbCellsX
                && cellY >= 0 && cellY < nbCellsY;
    }

    /**
     * Converts 2D cell coordinates to a 1D index for the explorationData array.
     *
     * @param cellX Cell X index.
     * @param cellY Cell Y index.
     * @return The corresponding index in the explorationData array.
     */
    private int index(int cellX, int cellY) {
        return cellY * nbCellsX + cellX;
    }

    /**
     * Returns {@code true} if any cell within {@code radiusCells} of the given world position is
     * {@link ExplorationState#REVEALED}.
     *
     * @param worldX      World X coordinate of the centre.
     * @param worldZ      World Z coordinate of the centre.
     * @param radiusCells Radius in cells.
     * @return Whether any nearby cell is revealed.
     */
    public boolean isWorldPosExplored(double worldX, double worldZ, int radiusCells) {
        int cx = toCellX(worldX);
        int cz = toCellZ(worldZ);

        for (int dx = -radiusCells; dx <= radiusCells; dx++) {
            for (int dy = -radiusCells; dy <= radiusCells; dy++) {
                if (dx * dx + dy * dy <= radiusCells * radiusCells) {
                    int cellX = cx + dx;
                    int cellY = cz + dy;
                    if (inBounds(cellX, cellY) && stateAt(cellX, cellY) == ExplorationState.REVEALED)
                        return true;
                }
            }
        }
        return false;
    }

    /**
     * Returns {@code true} if at least one cell intersecting the given world-space rectangle is
     * {@link ExplorationState#REVEALED}.
     *
     * @param topLeftX    World-space top-left X of the region.
     * @param topLeftZ    World-space top-left Z of the region.
     * @param width       Region width in world units (blocks).
     * @param height      Region height in world units (blocks).
     * @param radiusCells Optional radius in cells to expand the region by.
     * @return Whether any intersecting exploration cell is revealed.
     */
    public boolean regionExplored(double topLeftX, double topLeftZ, double width, double height, int radiusCells) {

        double minX = Math.min(topLeftX, topLeftX + width);
        double maxX = Math.max(topLeftX, topLeftX + width);
        double minZ = Math.min(topLeftZ, topLeftZ + height);
        double maxZ = Math.max(topLeftZ, topLeftZ + height);

        // The max edge is exclusive for regions; nudge it inward to avoid selecting the next cell.
        if (maxX > minX) maxX = Math.nextDown(maxX);
        if (maxZ > minZ) maxZ = Math.nextDown(maxZ);

        int minCellX = toCellX(minX) - radiusCells;
        int maxCellX = toCellX(maxX) + radiusCells;
        int minCellZ = toCellZ(minZ) - radiusCells;
        int maxCellZ = toCellZ(maxZ) + radiusCells;

        if (maxCellX < 0 || maxCellZ < 0 || minCellX >= nbCellsX || minCellZ >= nbCellsY) {
            return false;
        }

        minCellX = Math.max(0, minCellX);
        maxCellX = Math.min(nbCellsX - 1, maxCellX);
        minCellZ = Math.max(0, minCellZ);
        maxCellZ = Math.min(nbCellsY - 1, maxCellZ);

        for (int cellX = minCellX; cellX <= maxCellX; cellX++) {
            for (int cellZ = minCellZ; cellZ <= maxCellZ; cellZ++) {
                if (stateAt(cellX, cellZ).ordinal() >= ExplorationState.VISIBLE.ordinal()) {
                    return true;
                }
            }
        }

        return false;
    }

    /**
     * Sets the exploration state of a single cell.
     *
     * @param cellX Cell X index.
     * @param cellY Cell Y index.
     * @param state The new state.
     */
    public void markCell(int cellX, int cellY, ExplorationState state) {
        markCell(cellX, cellY, state, 0);
    }

    /**
     * Sets the exploration state for a cell and all cells within {@code range} cells of it.
     *
     * @param cellX Cell X index.
     * @param cellY Cell Y index.
     * @param state The new state.
     * @param range Radius in cells; 0 means only the target cell.
     */
    public void markCell(int cellX, int cellY, ExplorationState state, int range) {
        if (!inBounds(cellX, cellY)) return;

        if (range == 0) {
            updateExplorationState(cellX, cellY, state);
        } else {
            for (int dx = -range; dx <= range; dx++) {
                for (int dy = -range; dy <= range; dy++) {
                    if (dx * dx + dy * dy <= range * range) {
                        updateExplorationState(cellX + dx, cellY + dy, state);
                    }
                }
            }
        }
    }

    /**
     * Updates the exploration state of a single cell and marks it as dirty for texture upload.
     *
     * @param cellX Cell X index.
     * @param cellY Cell Y index.
     * @param state The new state.
     */
    private void updateExplorationState(int cellX, int cellY, ExplorationState state) {
        var index = index(cellX, cellY);
        if (index < 0 || index >= explorationData.length) {
            LOGGER.warn("Attempted to update exploration state for out-of-bounds cell ({}, {})", cellX, cellY);
            return;
        }
        explorationData[index] = state.getValue();
        dirtyCells.add(index);
    }

    /**
     * Releases all GPU and native memory held by this instance.
     * After calling this method the instance must not be used.
     * Should be called on (or via) the render thread.
     */
    public void dispose() {

        if (fogTexture != null) {

            if (fogTextureId != null) {

                Client.mc().getTextureManager()
                        .destroyTexture(fogTextureId);

                fogTextureId = null;
            }

            fogTexture.close();
            fogTexture = null;
        }

        if (fogMask != null) {

            fogMask.close();
            fogMask = null;
        }

        dirtyCells.clear();
    }

    /**
     * Returns the world X coordinate of the centre of the given cell column.
     *
     * @param cellX Cell X index.
     * @return World X of the cell centre.
     */
    public double cellCenterX(int cellX) {
        return xMin + cellX * (double) cellSize + cellSize / 2.0;
    }

    /**
     * Returns the world Z coordinate of the centre of the given cell row.
     *
     * @param cellZ Cell Z (Y) index.
     * @return World Z of the cell centre.
     */
    public double cellCenterZ(int cellZ) {
        return zMin + cellZ * (double) cellSize + cellSize / 2.0;
    }
}