/*
 * This file is part of ArdaMaps, licensed under the MIT License (MIT).
 *
 * Copyright (c) Paul-Bantz <https://github.com/Paul-Bantz>
 * Copyright (c) contributors
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

package com.duom.ardamaps.core.data;

import com.duom.ardamaps.ArdaMapsClient;
import com.duom.ardamaps.core.Client;
import com.duom.ardamaps.core.data.config.Dimension;
import com.mojang.blaze3d.platform.NativeImage;
import lombok.Getter;
import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;
import net.minecraft.client.Minecraft;
import net.minecraft.client.renderer.texture.DynamicTexture;
import net.minecraft.resources.Identifier;
import org.jetbrains.annotations.Nullable;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.Serial;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Manages the player's exploration state for a single dimension, including which areas have been
 * explored and the corresponding fog-of-war texture.
 *
 * <p>Each dimension has its own {@code PlayerExploration} instance, registered in
 * {@link com.duom.ardamaps.core.data.config.client.ClientConfig}.</p>
 */
@Environment(EnvType.CLIENT)
public class PlayerExploration implements Serializable {

    /** Class logger */
    private static final Logger LOGGER = LoggerFactory.getLogger(PlayerExploration.class);

    @Serial
    private static final long serialVersionUID = 1L;

    /** Prefix used when registering the fog-of-war texture in Minecraft's texture manager. */
    private static final String TEXTURE_PREFIX = "fog_of_war_texture";

    /** The dimension ID this instance manages (e.g. {@code "minecraft:overworld"}). */
    @Getter
    private final String dimensionId;

    /** Optional vertical range index this instance manages. Null for non-ranged dimensions. */
    @Getter
    private final Integer rangeIndex;

    /** Number of cells along the X axis (width) of the dimension. */
    @Getter
    private final int nbCellsX;

    /** Number of cells along the Z axis (height) of the dimension. */
    @Getter
    private final int nbCellsY;

    /** The world X coordinate corresponding to the minimum cell X index (0). */
    private final int xMin;

    /** The world Z coordinate corresponding to the minimum cell Y index (0). */
    private final int zMin;

    /** Whether this instance was automatically generated (true) or loaded from saved data (false). */
    @Getter
    private final boolean autoGenerated;

    /**
     * Size of each exploration cell in world units (blocks), computed at construction time.
     * Delegated to {@link ExplorationGrid}, which keeps the grid within its maximum cell count.
     */
    @Getter
    private final int cellSize;

    /**
     * The backing byte array that stores the exploration state for each cell.
     */
    private byte[] explorationData;

    /** Pure grid delegate rebuilt from persisted fields after deserialization. */
    private transient ExplorationGrid grid;

    /** Set of cell indices that have been modified since the last texture upload. */
    private transient Set<Integer> dirtyCells;

    /**
     * The in-memory (CPU-side) fog-of-war mask image, where each pixel corresponds to a cell.
     * This is updated on the go and used by {@link #fogTexture} to upload changes to the GPU.
     */
    private transient NativeImage fogMask;

    /** The GPU texture for the fog-of-war, created from {@link #fogMask}. */
    private transient DynamicTexture fogTexture;

    /** The identifier of the fog-of-war texture in Minecraft's texture manager, used for rendering. */
    @Getter
    private transient Identifier fogTextureId;

    /**
     * Creates a new {@link PlayerExploration} for the given dimension.
     *
     * <p>The {@code explorationData} array is used as-is (not copied) so that mutations are
     * visible to whatever holds the same reference (e.g.
     * {@link com.duom.ardamaps.core.data.config.client.ClientProgress}).</p>
     *
     * @param dimension  Dimension definition providing world extents.
     * @param rangeIndex Optional vertical range index, or null for non-ranged dimensions.
     */
    private PlayerExploration(Dimension dimension, Integer rangeIndex) {

        this.dimensionId = dimension.getId();
        this.rangeIndex = rangeIndex;
        ExplorationGrid grid = ExplorationGrid.create(dimension, null);
        this.cellSize = grid.getCellSize();
        this.nbCellsX = grid.getNbCellsX();
        this.nbCellsY = grid.getNbCellsY();
        this.xMin = dimension.getXMin();
        this.zMin = dimension.getZMin();
        this.autoGenerated = dimension.isAutoGenerated();
        this.explorationData = grid.getExplorationData();
        this.grid = grid;
        this.dirtyCells = new HashSet<>();
    }

    /**
     * Factory method to create a PlayerExploration instance for the dimension with the given ID.
     *
     * @param dimensionId The ID of the dimension (e.g. "minecraft:overworld").
     * @return A new PlayerExploration instance for the specified dimension, or null if the dimension is not found in the config.
     */
    public static @Nullable PlayerExploration create(String dimensionId) {

        var dimension = ArdaMapsClient.CONFIG.getDimension(dimensionId);

        if (dimension != null)
            return create(dimension, null);

        return null;
    }

    /**
     * Factory method to create a PlayerExploration instance for the given dimension and exploration data, with an option to mark it as auto-generated.
     *
     * @param dimension       Dimension definition providing world extents.
     * @param explorationData Backing array; length must equal nbCellsX * nbCellsY, or null to create an empty exploration.
     * @return A new PlayerExploration instance initialized with the provided data and auto-generation flag.
     */
    public static PlayerExploration create(Dimension dimension, byte[] explorationData) {

        return create(dimension, null, explorationData);
    }

    /**
     * Factory method to create a PlayerExploration instance for the given dimension, range and exploration data.
     *
     * @param dimension       Dimension definition providing world extents.
     * @param rangeIndex      The vertical range index, or null for non-ranged dimensions.
     * @param explorationData Backing array; length must equal nbCellsX * nbCellsY, or null to create an empty exploration.
     * @return A new PlayerExploration instance initialized with the provided data and auto-generation flag.
     */
    public static PlayerExploration create(Dimension dimension, Integer rangeIndex, byte[] explorationData) {

        PlayerExploration playerExploration = new PlayerExploration(dimension, rangeIndex);

        // Check if input data matches the computed cell-size. If not, we warn, ignore it and start fresh.
        int nbCells = (int) Math.ceil((double) dimension.getWidth() / playerExploration.getCellSize())
                * (int) Math.ceil((double) dimension.getHeight() / playerExploration.getCellSize());

        if (explorationData == null || explorationData.length != nbCells) {

            LOGGER.warn("Invalid exploration data - expected length {}, got {}. Creating empty exploration.", nbCells, explorationData == null ? "null" : explorationData.length);
            playerExploration.setExplorationData(null);

        } else {

            LOGGER.info("Initializing exploration with provided data of length {} for dimension '{}' range '{}'.", explorationData.length, dimension.getId(), rangeIndex);
            playerExploration.setExplorationData(explorationData);
        }

        playerExploration.initializeTexture();

        return playerExploration;
    }

    /**
     * Initializes the fog-of-war texture and synchronizes it with the current exploration data.
     * Should be called on (or via) the render thread after creating a PlayerExploration instance.
     */
    public void initializeTexture() {

        if (dirtyCells == null)
            dirtyCells = new HashSet<>();

        initialize();
        syncTextureFromData();
    }

    /**
     * Initializes the fog-of-war texture. All pixels begin as {@link ExplorationState#HIDDEN}.
     * No fill needed - NativeImage is zero-initialized, and HIDDEN colour is 0x00000000
     * Should be called on (or via) the render thread.
     */
    private void initialize() {

        releaseTextureResources();

        fogMask = new NativeImage(nbCellsX, nbCellsY, true);

        fogTexture = new DynamicTexture(this::textureName, fogMask);
        fogTextureId = com.duom.ardamaps.gui.ModConstants.modId(textureName());
        Minecraft.getInstance()
                .getTextureManager()
                .register(fogTextureId, fogTexture);
    }

    /**
     * Marks every non-{@link ExplorationState#HIDDEN} cell from {@link #explorationData} as dirty
     * and then calls {@link #flushTexture()} to upload them.
     *
     * <p>Call this once after {@link #initialize()} to restore a previously saved exploration state
     * onto the fog-of-war texture.</p>
     */
    public void syncTextureFromData() {

        var grid = grid();
        for (int i = 0; i < explorationData.length; i++) {
            if (ExplorationState.fromValue(grid.getExplorationData()[i]) != ExplorationState.HIDDEN) {
                dirtyCells.add(i);
            }
        }
        flushTexture();
    }

    /**
     * @return The dynamic texture name for this exploration range.
     */
    private String textureName() {

        String name = TEXTURE_PREFIX + "_" + sanitizeIdentifierSuffix(dimensionId);
        if (rangeIndex != null) name += "_" + rangeIndex;
        return name;
    }

    /**
     * Uploads all dirty cells to the fog-of-war texture.
     * No-op if there are no dirty cells or if the texture has not been initialized.
     */
    public void flushTexture() {
        if (dirtyCells == null || dirtyCells.isEmpty() || fogMask == null) return;

        var grid = grid();
        for (int idx : dirtyCells) {
            int x = idx % nbCellsX;
            int y = idx / nbCellsX;
            fogMask.setPixel(x, y, grid.stateAt(x, y).getColor());
        }

        dirtyCells.clear();
        fogTexture.upload();
    }

    /**
     * Sanitizes the dimension ID to ensure it's a valid texture identifier suffix by replacing
     *
     * @param value The original dimension identifier (e.g. "minecraft:overworld").
     * @return A sanitized version of the dimension ID suitable for use in texture identifiers (e.g. "minecraft_overworld").
     */
    private String sanitizeIdentifierSuffix(String value) {

        StringBuilder sanitized = new StringBuilder(value.length());

        for (int idx = 0; idx < value.length(); idx++) {
            char c = Character.toLowerCase(value.charAt(idx));

            if ((c >= 'a' && c <= 'z')
                    || (c >= '0' && c <= '9')
                    || c == '/'
                    || c == '.'
                    || c == '_'
                    || c == '-') {
                sanitized.append(c);
            } else {
                sanitized.append('_');
            }
        }

        return sanitized.toString();
    }

    /**
     * Returns the exploration state of the cell at {@code (cellX, cellY)}.
     *
     * @param cellX Cell X index.
     * @param cellY Cell Y index.
     * @return The {@link ExplorationState}, or {@link ExplorationState#HIDDEN} if out of bounds.
     */
    public ExplorationState stateAt(int cellX, int cellY) {

        return grid().stateAt(cellX, cellY);
    }

    /**
     * Sets the backing exploration data and resets the pure grid delegate.
     *
     * @param explorationData Backing exploration data.
     */
    public void setExplorationData(byte[] explorationData) {

        this.grid = ExplorationGrid.create(xMin, zMin, cellSize, nbCellsX, nbCellsY, explorationData);
        this.explorationData = grid.getExplorationData();
    }

    /**
     * @return The pure grid delegate, rebuilding it after JSON deserialization if needed.
     */
    private ExplorationGrid grid() {

        if (grid == null) {
            grid = ExplorationGrid.create(xMin, zMin, cellSize, nbCellsX, nbCellsY, explorationData);
            explorationData = grid.getExplorationData();
        }

        return grid;
    }

    /**
     * Factory method to create a PlayerExploration instance for a ranged dimension.
     *
     * @param dimensionId The ID of the dimension.
     * @param rangeIndex  The vertical range index, or null for non-ranged dimensions.
     * @return A new PlayerExploration instance, or null if the dimension is not found in the config.
     */
    public static @Nullable PlayerExploration create(String dimensionId, Integer rangeIndex) {

        var dimension = ArdaMapsClient.CONFIG.getDimension(dimensionId);

        if (dimension != null)
            return create(dimension, rangeIndex, null);

        return null;
    }

    /**
     * Returns the exploration state at the given world position.
     *
     * @param worldX World X coordinate.
     * @param worldZ World Z coordinate.
     * @return The {@link ExplorationState}, or {@link ExplorationState#HIDDEN} if out of bounds.
     */
    public ExplorationState stateAtWorldPos(double worldX, double worldZ) {
        return grid().stateAtWorldPos(worldX, worldZ);
    }

    /**
     * Converts a world X coordinate to the cell-X index.
     *
     * @param worldX World X coordinate.
     * @return Cell X index (may be out of bounds).
     */
    public int toCellX(double worldX) {
        return grid().toCellX(worldX);
    }

    /**
     * Converts a world Z coordinate to the cell-Y index.
     *
     * @param worldZ World Z coordinate.
     * @return Cell Y index (may be out of bounds).
     */
    public int toCellZ(double worldZ) {
        return grid().toCellZ(worldZ);
    }

    /**
     * Returns {@code true} if any cell within {@code radiusCells} of the given world position is
     * {@link ExplorationState#REVEALED}.
     *
     * @param worldX      World X coordinate of the centre.
     * @param worldZ      World Z coordinate of the centre.
     * @param radiusCells Radius in cells.
     * @return Whether any nearby cell is revealed.
     */
    public boolean isWorldPosExplored(double worldX, double worldZ, int radiusCells) {
        return grid().isWorldPosExplored(worldX, worldZ, radiusCells);
    }

    /**
     * Returns {@code true} if at least one cell intersecting the given world-space rectangle is
     * {@link ExplorationState#REVEALED}.
     *
     * @param topLeftX    World-space top-left X of the region.
     * @param topLeftZ    World-space top-left Z of the region.
     * @param width       Region width in world units (blocks).
     * @param height      Region height in world units (blocks).
     * @param radiusCells Optional radius in cells to expand the region by.
     * @return Whether any intersecting exploration cell is revealed.
     */
    public boolean regionExplored(double topLeftX, double topLeftZ, double width, double height, int radiusCells) {
        return grid().regionExplored(topLeftX, topLeftZ, width, height, radiusCells);
    }

    /**
     * Sets the exploration state of a single cell.
     *
     * @param cellX Cell X index.
     * @param cellY Cell Y index.
     * @param state The new state.
     */
    public void markCell(int cellX, int cellY, ExplorationState state) {
        markCell(cellX, cellY, state, 0);
    }

    /**
     * Sets the exploration state for a cell and all cells within {@code range} cells of it.
     *
     * @param cellX Cell X index.
     * @param cellY Cell Y index.
     * @param state The new state.
     * @param range Radius in cells; 0 means only the target cell.
     */
    public void markCell(int cellX, int cellY, ExplorationState state, int range) {

        if (dirtyCells == null) dirtyCells = new HashSet<>();
        dirtyCells.addAll(grid().markCell(cellX, cellY, state, range));
    }

    /**
     * Releases all GPU and native memory held by this instance.
     * After calling this method the instance must not be used.
     * Should be called on (or via) the render thread.
     */
    public void dispose() {

        releaseTextureResources();

        if (dirtyCells != null) dirtyCells.clear();
    }

    /**
     * Releases GPU and native texture resources without changing grid data.
     */
    private void releaseTextureResources() {

        if (fogTexture != null) {

            if (fogTextureId != null) {

                Client.mc().getTextureManager()
                        .release(fogTextureId);

                fogTextureId = null;
            }

            fogTexture.close();
            fogTexture = null;
        }

        if (fogMask != null) {

            fogMask.close();
            fogMask = null;
        }

    }

    /**
     * Returns the world X coordinate of the centre of the given cell column.
     *
     * @param cellX Cell X index.
     * @return World X of the cell centre.
     */
    public double cellCenterX(int cellX) {
        return grid().cellCenterX(cellX);
    }

    /**
     * Returns the world Z coordinate of the centre of the given cell row.
     *
     * @param cellZ Cell Z (Y) index.
     * @return World Z of the cell centre.
     */
    public double cellCenterZ(int cellZ) {
        return grid().cellCenterZ(cellZ);
    }
}
